export {AddCompetitionLabel} from "./addCompetitionLabel/AddCompetitionLabel"
export {PageTitle} from "./pageTitle/PageTitle"
export {LoginLabel} from "./loginLabel/LoginLabel"
export {LoginInput} from "./loginInput/LoginInput"
export {CompetitionDetailLabel} from "./competitionLabel/CompetitionDetailLabel"
export {RegitUpdateDeleteButton} from "./regitUpdateDeleteButton/RegitUpdateDeleteButton"
