import { MockDataType } from "../type";

export const mockData: MockDataType = {
  totalPages: 2,
  totalPosts: 20,
  posts: [
    {
      postId: 134,
      title: "뉴스공지3",
      content: "대회 관련해서 문의드립니다.",
      writer: "이브라히모비치",
      createAt: "2024-06-23",
    },
    {
      postId: 31,
      title: "경기 일정 관련해서 문의 남겨요",
      content: "경기 일정 관련해서 문의 남겨요",
      writer: "이브라히모비치",
      createAt: "2024-02-25",
    },
    {
      postId: 32,
      title: "주변에 식사 할 곳 있나요??",
      content: "주변에 식사 할 곳 있나요??",
      writer: "이브라히모비치",
      createAt: "2024-02-25",
    },
    {
      postId: 33,
      title: "OOO 선수 이번에 참가하나요?",
      content: "OOO 선수 이번에 참가하나요?",
      writer: "이브라히모비치",
      createAt: "2024-02-25",
    },
    {
      postId: 88,
      title: "뉴스공지3",
      content: "뉴스공지3",
      writer: "이브라히모비치",
      createAt: "2024-06-12",
    },
    {
      postId: 85,
      title: "농구협회 심판 등록 관련 문의는 어디에 하면 되나요?",
      content: "농구협회 심판 등록 관련 문의는 어디에 하면 되나요?",
      writer: "이브라히모비치",
      createAt: "2024-06-12",
    },
    {
      postId: 83,
      title: "후원 문의는 어디에 하나여?",
      content: "후원 문의는 어디에 하나여?",
      writer: "이브라히모비치",
      createAt: "2024-06-10",
    },
    {
      postId: 82,
      title: "뉴스공지3",
      content: "뉴스공지3",
      writer: "이브라히모비치",
      createAt: "2024-06-10",
    },
    {
      postId: 76,
      title: "OOO 경기 티켓은 어디에서 구매할 수 있나요??",
      content: "OOO 경기 티켓은 어디에서 구매할 수 있나요??",
      writer: "이브라히모비치",
      createAt: "2024-06-10",
    },
    {
      postId: 58,
      title: "OOO 경기 티켓은 어디에서 구매할 수 있나요??",
      content: "OOO 경기 티켓은 어디에서 구매할 수 있나요??",
      writer: "이브라히모비치",
      createAt: "2024-03-18",
    },
    {
      postId: 59,
      title: "OOO 경기 티켓은 어디에서 구매할 수 있나요??",
      content: "OOO 경기 티켓은 어디에서 구매할 수 있나요??",
      writer: "이브라히모비치",
      createAt: "2024-03-18",
    },
    {
      postId: 61,
      title: "OOO 경기 티켓은 어디에서 구매할 수 있나요??",
      content: "OOO 경기 티켓은 어디에서 구매할 수 있나요??",
      writer: "이브라히모비치",
      createAt: "2024-03-18",
    },
    {
      postId: 34,
      title: "OOO 경기 티켓은 어디에서 구매할 수 있나요??",
      content: "OOO 경기 티켓은 어디에서 구매할 수 있나요??",
      writer: "이브라히모비치",
      createAt: "2024-02-25",
    },
    {
      postId: 35,
      title: "OOO 경기 티켓은 어디에서 구매할 수 있나요??",
      content: "OOO 경기 티켓은 어디에서 구매할 수 있나요??",
      writer: "이브라히모비치",
      createAt: "2024-02-25",
    },
  ],
};
